apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.0" # Check latest version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin
    persistence:
      enabled: true
      size: 10Gi
    sidecar:
      dashboards:
        enabled: true